[project]
name = "belo-horizonte"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dowhy>=0.14",
    "earthengine-api>=1.7.1",
    "geedim>=2.0.0",
    "geemap>=0.36.6",
    "geopandas>=1.1.1",
    "ipykernel<7",
    "matplotlib>=3.10.7",
    "networkx>=3.6",
    "openpyxl>=3.1.5",
    "psmpy>=0.3.16",
    "rasterio>=1.4.3",
    "seaborn>=0.13.2",
]


[tool.ruff.lint]
select = ["ALL"]
ignore = ["D", "PD010"]

[tool.basedpyright]
typeCheckingMode = "standard"
ignore = ["**/*.ipynb"]
